  workflows:
    android-build:
      name: Android Build
      max_build_duration: 60
      instance_type: linux_x2
      environment:
        node: 18
        java: 17
      scripts:
        - name: Install dependencies
          script: npm install
        - name: Build Android
          script: |
            npx cap sync android
            cd android
            ./gradlew assembleDebug
      artifacts:
        - android/app/build/outputs/**/*.apk